/*
 * File: main.c
 * Author: i-monroy
 *
 * Project:
 *     Dual Button Interrupt (Pull-Up and Pull-Down)
 *
 * Description:
 *     Controls two onboard LEDs using two external GPIO interrupts.
 *     Button 1 controls an LED while held, and Button 2 toggles an LED.
 *
 * Hardware:
 *     MSP432P401R LaunchPad
 *
 * LEDs:
 *     P1.0 - Onboard red LED
 *     P2.0 - Red channel of the onboard RGB LED
 *
 * Button Interrupts:
 *     P4.1 - External button configured with an internal pull-up resistor
 *     P4.6 - External button configured with an internal pull-down resistor
 *
 * IDE:
 *     Code Composer Studio (CCS) 12.8.1
 */

#include "msp.h"

/* Short delay used to reduce mechanical button bounce. */
#define BUTTON_DEBOUNCE_DELAY_CYCLES (150000U)

/* Function Prototypes */
void LED_redLEDsInit(void);
void Button_pullUpButtonInit(void);
void Button_pullDownButtonInit(void);

/* Main */
int main(void)
{
    /* Stop the watchdog timer to prevent periodic resets. */
    WDT_A->CTL = WDT_A_CTL_PW | WDT_A_CTL_HOLD;

    /* Configure the onboard red LEDs. */
    LED_redLEDsInit();

    /* Configure the external pull-up and pull-down button interrupts. */
    Button_pullUpButtonInit();
    Button_pullDownButtonInit();

    /* Enable Port 4 interrupts in the NVIC. See README Section 4.5. */
    NVIC_EnableIRQ(PORT4_IRQn);

    /* Enable interrupts globally. See README Section 4.5. */
    __enable_irq();

    while (1)
    {
        /*
        * No polling is required here. Button events are handled
        * by the Port 4 interrupt service routine. See README Section 4.5.
        */
    }
}

/* Configure P1.0 and P2.0 as outputs for the onboard red LEDs. */
void LED_redLEDsInit(void)
{
    /* Configure both LED pins for GPIO operation. */
    P1->SEL0 &= ~BIT0;
    P1->SEL1 &= ~BIT0;

    P2->SEL0 &= ~BIT0;
    P2->SEL1 &= ~BIT0;

    /* Configure both LED pins as outputs. */
    P1->DIR |= BIT0;
    P2->DIR |= BIT0;

    /* Start with both LEDs turned off. */
    P1->OUT &= ~BIT0;
    P2->OUT &= ~BIT0;
}

/*
 * Configure P4.1 as an active-low button input using
 * an internal pull-up resistor.
 */
void Button_pullUpButtonInit(void)
{
    /* Configure P4.1 for GPIO operation. */
    P4->SEL0 &= ~BIT1;
    P4->SEL1 &= ~BIT1;

    /* Configure P4.1 as an input. */
    P4->DIR &= ~BIT1;

    /* Enable the internal resistor and select pull-up operation. */
    P4->REN |= BIT1;
    P4->OUT |= BIT1;

    /*
     * Initially detect the high-to-low edge caused by pressing
     * the pull-up button. See README Section 4.4.
     */
    P4->IES |= BIT1;

    /* Clear any pending P4.1 interrupt flag. */
    P4->IFG &= ~BIT1;

    /* Enable interrupt generation for P4.1. */
    P4->IE |= BIT1;
}

/*
 * Configure P4.6 as an active-high button input using
 * an internal pull-down resistor.
 */
void Button_pullDownButtonInit(void)
{
    /* Configure P4.6 for GPIO operation. */
    P4->SEL0 &= ~BIT6;
    P4->SEL1 &= ~BIT6;

    /* Configure P4.6 as an input. */
    P4->DIR &= ~BIT6;

    /* Enable the internal resistor and select pull-down operation. */
    P4->REN |= BIT6;
    P4->OUT &= ~BIT6;

    /*
     * Detect the low-to-high edge caused by pressing
     * the pull-down button. See README Section 4.4.
     */
    P4->IES &= ~BIT6;

    /* Clear any pending P4.6 interrupt flag. */
    P4->IFG &= ~BIT6;

    /* Enable interrupt generation for P4.6. */
    P4->IE |= BIT6;
}

/*
 * Handle interrupt requests generated by P4.1 and P4.6.
 * See README Section 4.6.
 */
void PORT4_IRQHandler(void)
{
    /*
     * Check whether P4.1 generated an interrupt.
     * See README Section 4.7.
     */
    if ((P4->IFG & BIT1) != 0U)
    {
        /* Allow the button signal time to settle. */
        __delay_cycles(BUTTON_DEBOUNCE_DELAY_CYCLES);

        /*
         * Read the current P4.1 input state to determine whether
         * the button was pressed or released. See README Section 4.8.
         */
        if ((P4->IN & BIT1) == 0U)
        {
            /* Button pressed: turn the red LED on. */
            P1->OUT |= BIT0;

            /*
             * Change edge detection to low-to-high so the next
             * interrupt detects the button release.
             * See README Section 4.9.
             */
            P4->IES &= ~BIT1;
        }
        else
        {
            /* Button released: turn the red LED off. */
            P1->OUT &= ~BIT0;

            /*
             * Change edge detection to high-to-low so the next
             * interrupt detects another button press.
             * See README Section 4.9.
             */
            P4->IES |= BIT1;
        }

        /* Clear the P4.1 interrupt flag. */
        P4->IFG &= ~BIT1;
    }

    /*
     * Check whether P4.6 generated an interrupt.
     * See README Section 4.7.
     */
    if ((P4->IFG & BIT6) != 0U)
    {
        /* Allow the button signal time to settle. */
        __delay_cycles(BUTTON_DEBOUNCE_DELAY_CYCLES);

        /*
         * Confirm that the active-high pull-down button is pressed.
         * See README Section 4.8.
         */
        if ((P4->IN & BIT6) != 0U)
        {
            /* Toggle the red channel of the onboard RGB LED. */
            P2->OUT ^= BIT0;
        }

        /* Clear the P4.6 interrupt flag. */
        P4->IFG &= ~BIT6;
    }
}
